# Site settings
title: alanp.ca
tagline: thoughts on software development & startups
email: contact@alanp.ca
description: alanp.ca - thoughts on software development & startups
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://alanp.ca" # the base hostname & protocol for your site
twitter_username: alanpca
github_username:  alanpca
linkedin_base: http://ca.linkedin.com/in/
linkedin_username: alanlaudicina
permalink: :year/:month/:day/:title/
password: wompwomp # LOL just kidding
paginate: 3
paginate_path: "pages/:num/"
name: Alan P. Laudicina

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  use_coderay: true

  coderay:
    coderay_line_numbers: table
    coderay_line_numbers_start: 1
    coderay_css: class
